site_name: One Last Kiss
site_dir: 'site'
site_url: https://localhost:8000/

repo_name: aletolia/aletolia.github.io # 仓库名称
repo_url: https://github.com/aletolia/aletolia.github.io.git # 仓库地址

theme:
  # logo: assets\saber.ico
  favicon: img/favicon.ico
  logo: img/icon.png
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss # 可以叉掉公告的功能
    - content.action.edit # 编辑按钮，似乎没啥用
    - content.action.view # 查看按钮，似乎没啥用
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    - content.code.select # 选择代码按钮
    # - content.tabs.link # 链接标签
    - content.tooltips # 不太清楚呢这个
    # - header.autohide # 自动隐藏header
    - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    # - navigation.prune # 只构建可见的页面
    - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - 🏠 Home: 
    - index.md
  - ⛏️ CV and Multimodels:
    - Mygo.md
    - GMM.md
    - DINO.md
    - Mamba.md
    - ViT.md
    - Self-Supervised Learning MoCo.md
    - Self-Supervised Learning MoCoV2,3.md
    - Vision Transformer (一).md
    - Vision Transformer  (二).md
    - Vision Transformer (三).md
    - Vision Transformer (四) (TNT).md
    - Vision Transformer (知识蒸馏 预训练）.md
    - Vision Transformer (PyramidTNT).md
    - 傅里叶级数和傅里叶变换专题.md
    - Python 存储与读取 HDF5 文件.md
    - Segment Anything in Medical Images.md
    - Vision Mamba Efficient Visual Representation Learning with Bidirectional State Space Model.md
    - DeepSeekMoE Towards Ultimate Expert Specialization in Mixture-of-Experts Language Models .md
    
    - 🚑 医学影像相关:
      - Why is the winner the best.md
      - PORPOISE.md
      - HIPT.md
      - Data-efficient and weakly supervised computational pathology on whole-slide images(CLAM).md
      - Towards a general-purpose foundation model for computational pathology.md
      - A whole-slide foundation model for digital pathology from real-world data.md
      - A visual-language foundation model for computational pathology.md
      - Recurrent memory with optimal polynomial projections..md
      - Modeling Dense Multimodal Interactions Between Biological Pathways and Histology for Survival Prediction.md
      - Inferring super-resolution tissue architecture by integrating spatial transcriptomics with histology.md
      - Prediction of recurrence risk in endometrial cancer with multimodal deep learning.md
    - 📖 Anthropic 可解释性译集:
      - "通过特征交互追踪注意力计算": anth-interp/attention-qk-zh/index.md
      - "大语言模型的生物学": anth-interp/attribution-graphs-biology-zh/index.md
      - "电路追踪：揭示语言模型中的计算图": anth-interp/attribution-graphs-methods-zh/index.md
      - "追踪大语言模型的思考": anth-interp/circuit-tracing-zh/index.md
      - "跨层转码器模型差异比较的洞见": anth-interp/crosscoder-diffing-update-zh/index.md
      - "跨层特征与模型差异比较的稀疏跨层转码器": anth-interp/crosscoders-zh/index.md
      - "曲线检测器": anth-interp/distill-curve-detectors-zh/index.md
      - "InceptionV1 早期视觉概述": anth-interp/distill-early-vision-zh/index.md
      - "神经网络中自然涌现的等变性": anth-interp/distill-equivariance-zh/index.md
      - "放大观察：电路导论": anth-interp/distill-zoom-in-zh/index.md
      - "情绪概念及其在大语言模型中的功能": anth-interp/emotions-zh/index.md
      - "规模化可解释性的工程挑战": anth-interp/engineering-challenges-zh/index.md
      - "评估特征引导：缓解社会偏见的案例研究": anth-interp/evaluating-feature-steering-zh/index.md
      - "机制（不）忠实性的玩具模型": anth-interp/faithfulness-toy-model-zh/index.md
      - "用字典学习特征作为分类器": anth-interp/features-as-classifiers-zh/index.md
      - "A Mathematical Framework for Transformer Circuits": anth-interp/framework-zh/index.md
      - "语言模型中的全局工作空间（A Global Workspace in Language Models）": anth-interp/global-workspace-zh/index.md
      - "HeadVis：注意力头可视化": anth-interp/headvis-zh/index.md
      - "上下文学习与归纳头（In-context Learning and Induction Heads）": anth-interp/icl-induction-heads-zh/index.md
      - "干涉权重的玩具模型": anth-interp/interference-weights-zh/index.md
      - "可解释性之梦（Interpretability Dreams）": anth-interp/interpretability-dreams-zh/index.md
      - "大语言模型中涌现的内省意识": anth-interp/introspection-zh/index.md
      - "当模型操纵流形：计数任务的几何": anth-interp/linebreaks-zh/index.md
      - "绘制大语言模型的内心地图": anth-interp/mapping-mind-zh/index.md
      - "机制可解释性、变量与可解释基的重要性": anth-interp/mech-interp-essay-zh/index.md
      - "分阶段模型差异比较": anth-interp/model-diffing-zh/index.md
      - "Towards Monosemanticity: Decomposing Language Models With Dictionary Learning": anth-interp/monosemanticity-zh/index.md
      - "自然语言自编码器": anth-interp/nla-zh/index.md
      - "开源电路追踪工具（Open-Sourcing Circuit-Tracing Tools）": anth-interp/open-source-circuit-tracing-zh/index.md
      - "人格向量：监测与控制语言模型中的性格特征": anth-interp/persona-vectors-zh/index.md
      - "transformer 残差流中的特权基": anth-interp/privileged-basis-zh/index.md
      - "质性研究的反思": anth-interp/qualitative-essay-zh/index.md
      - "规模化单语义性：从 Claude 3 Sonnet 中提取可解释特征": anth-interp/scaling-monosemanticity-zh/index.md
      - "Softmax 线性单元（Softmax Linear Units）": anth-interp/solu-zh/index.md
      - "分布式表示：组合与叠加": anth-interp/superposition-composition-zh/index.md
      - "叠加、记忆与双重下降": anth-interp/toy-double-descent-zh/index.md
      - "Toy Models of Superposition": anth-interp/toy-model-zh/index.md

  - 🚀 Re:0 Road to CPath & Visualization:
    - Session 1.ipynb
    - Session 2.ipynb
    - Session 3.ipynb
    - How to visualize Attention.md
    - AttentionViz A Global View of Transformer Attention.md
    - Transformer Interpretability Beyond Attention Visualization.md
    - Visualization Work Flow.md
    - Attention Generation Work Flow.md
    - 🪛 PyTorch:
      - Autograd mechanics — PyTorch 2_3 documentation.md
      - PyTorch Autograd Explained - In-depth Tutorial.md

  - 💤 Re:0 Road to scRNA-seq Analysis:

    - Using Python:
      - ⏳ CHAPTER 1 简介:
        - 1.1 Single-cell RNA sequencing.md
        - 1.2 Raw Data Processing.md
        - 1.3 Analysis frameworks and tools.md
      - 🌏 CHAPTER 2 数据准备与可视化:
        - 2.1 quality_control.ipynb
        - 2.2 normalization.ipynb
        - 2.3_feature_selection.ipynb
        - 2.4_dimensionality_reduction.ipynb
      - 🍀 CHAPTER 3 识别细胞结构:
        - 3.1clustering.ipynb
        - 3.2annotation.ipynb
        - 3.3integration.ipynb
      - ⏱️ CHAPTER 4 推断细胞轨迹:
        - pseudotemporal.ipynb
        - rna_velocity.ipynb
        - lineage_tracing.ipynb
      - 🎁 CHAPTER 5 应对特殊情况:
        - differential_gene_expression.ipynb
        - compositional.ipynb
        - gsea_pathway.ipynb
        - perturbation_modeling.ipynb
      - ⚙️ CHAPTER 6 机制建模:
        - gene_regulatory_networks.ipynb
        - cell_cell_communication.ipynb
      - 🔓 CHAPTER 7 反卷积:
        - bulk_deconvolution.ipynb
    - 简明易懂的单细胞分析流程（使用 R 语言）:
        - 前言.md
        - 环境配置.md
        - 1.1 构建单细胞 RNA-seq 分析环境.md
        - 1.2 R 环境安装.md
        - 1.3 Docker 安装.md
        - 1.4 在 Docker 中启动 Rstudio.md
        - 1.5 有关 Bioconductor.md
        - 2.1 R 的基本用法.md
        - 2.2 如何处理 DataFrame？.md
        - 2.3 使用 ggplot2 可视化数据.md
        - 3.1 PCA.md
        - 3.2 使用 clusterPlofiler 进行富集分析.md
        - 3.3 基因本体（GO）中各 BP、MF 和 CC 的富集分析.md
        - 3.3 使用 DEseq2 提取 RNA-seq 分析数据中的 DEG.md
        - 3.4 使用其他数据库（KEGG、Reactome 等）进行富集分析.md
        - 4.1 scRNA-seq 概要.md
        - 4.2 准备使用 Seurat 进行分析.md
        - 4.3 使用 Seurat 进行数据预处理.md
        - 4.4 使用 Seurat 进行数据分析的一般顺序.md
        - 5.1 如何查找单细胞 RNA-seq 数据.md
        - 5.2 为每个簇自动添加细胞注释标签.md
        - 5.3 使用 FeaturePlot 检查基因表达.md
        - 5.4 将单细胞 RNA-seq 数据集相互结合.md
        - 5.5 纠正批次效应，比较对照组和刺激组.md
        - 5.6 确定每个群组的标记基因.md
        - 6.1 如何使用 Cell Ranger 统计 scRNA-seq 数据中的基因表达水平.md
        - 6.2 使用 Cell Ranger 处理 NCBI Sequence Read Archive (SRA) 数据.md
        - 7.1 关于 scRNA-seq 数据的质量控制.md
        - 7.2 使用 DoubleFinder 检测双重细胞.md
        - 7.3 用 CellBender 去除背景 RNA.md

  - 🧬 scRNA Analysis:

    - 🐍 Using Python:
      - Large-scale foundation model on single-cell transcriptomics.md
      - scGPT toward building a foundation model for single-cell multi-omics using generative AI.md
      - scBERT as a large-scale pretrained deep language model for cell type annotation of single-cell RNA-seq data.md
      - RNA velocity of single cells.md
      - TFvelo_gene regulation inspired RNA velocity estimation.md
      - Disentanglement of single-cell data with biolord.md
      - ⭐⭐⭐C5aR1 inhibition reprograms tumor associated macrophages and reverses PARP inhibitor resistance in breast cancer.md
      - Spatial transition tensor of single cells.md
      - Statistical method scDEED for detecting dubious 2D single-cell embeddings and optimizing t-SNE and UMAP hyperparameters.md
      - scRank infers drug-responsive cell types from untreated scRNA-seq data using a target-perturbed gene regulatory network.md
    - 📔 文献:
      - ZNF689 deficiency promotes intratumor heterogeneity and immunotherapy resistance in triple-negative breast cancer.md
      - Tumour vasculature at single-cell resolution.md
      - scRNA-seq of gastric tumor shows complex intercellular interaction with an alternative T cell exhaustion trajectory（参考）.md
      - Single-cell analysis reveals new evolutionary complexity in uveal melanoma（参考 2）.md
      - Single-cell characterization of macrophages in uveal melanoma uncovers transcriptionally heterogeneous subsets conferring poor prognosis and aggressive behavior（范例 1）.md
      - ScRNA-seq of gastric cancer tissues reveals differences in the immune microenvironment of primary tumors and metastases.md
      - Blimp-1 and c-Maf regulate immune gene networks to protect against distinct pathways of pathobiont-induced colitis.md
      - Single cell analysis unveils B cell-dominated immune subtypes in HNSCC for enhanced prognostic and therapeutic stratification.md
      - Single-cell spatial multi-omics and deep learning dissect enhancer-driven gene regulatory networks in liver zonation.md
      - Neutrophil profiling illuminates anti-tumor antigen presenting potency.md
      - A blueprint for tumor-infiltrating B cells across human cancers.md
      - Single-cell transcriptomic analyses reveal distinct immune cell contributions to epithelial barrier dysfunction in checkpoint inhibitor colitis.md
      - Systematic dissection of tumor-normal single-cell ecosystems across a thousand tumors of 30 cancer types.md
      - The aged tumor microenvironment limits T cell control of cancer.md
      - TIM-3+ CD8 T cells with a terminally exhausted phenotype retain functional capacity in hematological malignancies.md
      - A lactate-SREBP2 signaling axis drives tolerogenic dendritic cell maturation and promotes cancer progression.md
      - A human omentum-specific mesothelial-like stromal population inhibits adipogenesis through IGFBP2 secretion.md
      - Interferon-stimulated neutrophils as a predictor of immunotherapy response.md
      - Repression of latent NF-κB enhancers by PDX1 regulates β cell functional heterogeneity.md
      - A systematic pan-cancer study on deep learning-based prediction of multi-omic biomarkers from routine pathology images.md
      - Single-cell and spatial transcriptomics analysis of non-small cell lung cancer.md
      - Seeing data as t-SNE and UMAP do.md      
      - Mapping the cellular biogeography of human bone marrow niches using single-cell transcriptomics and proteomic imaging.md
      - Onco-fetal Reprogramming of Endothelial Cells Drives Immunosuppressive Macrophages in Hepatocellular Carcinoma.md
      - Single-cell analysis of anti-BCMA CAR T cell therapy in patients with central nervous system autoimmunity.md
      - Single-cell sequencing depicts tumor architecture and empowers clinical decision in metastatic conjunctival melanoma.md
      - PR-SET7 epigenetically restrains uterine interferon response and cell death governing proper postnatal stromal development.md
      - Clonal associations between lymphocyte subsets and functional states in rheumatoid arthritis synovium.md

  - 📐 Data Structures:
    - 第 1 章 python 入门.md
    - 第 2 章 面向对象编程.md
    - 第 3 章 算法分析.md
    - 第 4 章 递归.md
    - 第 5 章 基于数组的序列.md
    - 第 6 章 栈、队列和双端队列.md
    - 第 7 章 链表(Linked Lists).md
    - 第 8 章 树 ★.md
    - 第 9 章 优先级队列.md

  - 💡 Reviews:
    - 🧭 scRNA analysis:
      - Best practices for single-cell analysis across modalities.md
      - Multi-omics integration in biomedical research – A metabolomics-centric review.md
      - Museum of spatial transcriptomics.md
      - A guide to artificial intelligence for cancer researchers.md
    - 🦠 Metabolism:
      - Metabolic analysis as a driver for discovery, diagnosis, and therapy.md
      - Metabolic heterogeneity in cancer.md
      - Toward modeling metabolic state from single-cell transcriptomics.md
      - Metabolic reprogramming and cancer progression.md
    - Protein:
      - Proteomic and interactomic insights into the molecular basis of cell functional diversity.md


extra:
  analytics:
    provider: google
    property: G-M0R7V8QGQ7

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.keys # 按键高亮，类似于行内代码那种，如 <kbd>Ctrl</kbd>，或者带图标的格式（强制小写）++ctrl++，也可组合 ++ctrl+s++（推荐第二种方式，第二种自带图标）
  - pymdownx.mark # 允许文本下划线，即 ^^Text^^
  - pymdownx.caret # 允许文本高亮，即 ==Text==
  - pymdownx.tilde
  - pymdownx.tasklist: # 允许 Todo 列表清单
      custom_checkbox: true # 允许修改其样式，不然用默认样式就很丑
      clickable_checkbox: true # 是否可通过点击切换状态（但无实际更改，只有视觉效果）

plugins: 
  - mkdocs-jupyter
  - search
  # - statistics: # 数据统计插件（pip install mkdocs-statistics-plugin）
  #     codelines_per_minute: 15 # 每分钟可看的代码行数
  #     words_per_minute: 150 # 每分钟可看的文本数



# 下面是提示块语法
# !!! note "可以双引号中指明标题"
#     随便多少缩进文本.

#     空行分段.
# !!! hint
#     标题会自动大写。
# !!! important ""
#     无标题提示块。
# !!! danger highlight blink "不要在家里做"
#     ...

# mkdocs.yml file

# other settings ...



# other settings ...

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - extra.js  
  - js/toggle_sidebar.js
  # - https://cdn.jsdelivr.net/npm/canvas-nest.js/dist/canvas-nest.js

extra_css: 
  - extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
# other settings ...
# Hello World




